# -*- coding: utf-8 -*-
"""Edades.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j63yzbCrFKQGReokglNWv1uBFiovQb7t
"""

sujeto1 = input ('Primer participante - escribe tu nombre: ')
edad1 = int(input('Cual es tu edad? '))
sujeto2 = input ('Segundo participante - escribe tu nombre: ')
edad2 = int(input('Cual es tu edad? '))

if edad1>edad2:
  print(sujeto1,'- es mayor')
elif edad1==edad2:
  print(sujeto1,'y', sujeto2, 'tienen la misma edad, no quieras engañarme!')
else:
  print(sujeto2, '- es mayor')