# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxiH-2ZTqWYGrv2DSpHU6dlbyd2PEmHL
"""

texto1 = input('Introduce un texto: ')
texto2 = texto1.lower()
texto3 = texto2.replace(' ','')

if (texto3==texto3[::-1]):
  print(texto1 + ' - Es un palindrome')
else:
  print(texto1 + ' - No es un palindrome')